# Generated by Django 5.2.8 on 2026-03-27 20:10

import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_invitation_accepted_invitation_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Admin', 'Admin'), ('Viewer', 'Viewer')], default='Member', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=projects.models.get_invitation_expiry),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
