# Generated by Django 5.2.8 on 2026-01-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetpin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetpin',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
