# Generated by Django 5.2.3 on 2025-12-09 12:27

from django.db import migrations

def update_task_statuses(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    # Update 'pending' to 'inprogress'
    Task.objects.filter(status='pending').update(status='inprogress')
    # Update 'in_progress' to 'inprogress'
    Task.objects.filter(status='in_progress').update(status='inprogress')

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_task_updated_at_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RunPython(update_task_statuses),
    ]
