# Generated by Django 5.2.8 on 2026-04-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('projects', '0003_remove_invitation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.invitation'),
        ),
    ]
