# Generated by Django 5.2.8 on 2026-04-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_related_invitation'),
        ('projects', '0003_remove_invitation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.invitation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('project_join', 'Project Join'), ('invite_accepted', 'Invite Accepted'), ('task_assign', 'Task Assigned'), ('deadline', 'Deadline Reminder'), ('system', 'System Notification')], max_length=50),
        ),
    ]
